# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  cline = nodeEnv.buildNodePackage {
    name = "cline";
    packageName = "cline";
    version = "1.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/cline/-/cline-1.0.1.tgz";
      sha512 = "2ON8BaRqNINpl4l3FeS9fOA47fq96GNUvYZ/Kfm6IaFsOHAE3DHIg0FDZVKYJn7VeHQcupPcsuJZr7ziONBbUw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Autonomous coding agent CLI - capable of creating/editing files, running commands, using the browser, and more";
      homepage = "https://cline.bot";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
