# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@opentelemetry/api-1.9.0" = {
      name = "_at_opentelemetry_slash_api";
      packageName = "@opentelemetry/api";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/api/-/api-1.9.0.tgz";
        sha512 = "3giAOQvZiH5F9bMlMiv8+GSPMeqg0dbaeo58/0SlA9sxSqZhnUtxzX9/2FzyhS9sWQf5S0GJE0AKBrFqjpeYcg==";
      };
    };
    "@opentelemetry/api-logs-0.57.2" = {
      name = "_at_opentelemetry_slash_api-logs";
      packageName = "@opentelemetry/api-logs";
      version = "0.57.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/api-logs/-/api-logs-0.57.2.tgz";
        sha512 = "uIX52NnTM0iBh84MShlpouI7UKqkZ7MrUszTmaypHBu4r7NofznSnQRfJ+uUeDtQDj6w8eFGg5KBLDAwAPz1+A==";
      };
    };
    "@opentelemetry/context-async-hooks-1.30.1" = {
      name = "_at_opentelemetry_slash_context-async-hooks";
      packageName = "@opentelemetry/context-async-hooks";
      version = "1.30.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/context-async-hooks/-/context-async-hooks-1.30.1.tgz";
        sha512 = "s5vvxXPVdjqS3kTLKMeBMvop9hbWkwzBpu+mUO2M7sZtlkyDJGwFe33wRKnbaYDo8ExRVBIIdwIGrqpxHuKttA==";
      };
    };
    "@opentelemetry/core-1.30.1" = {
      name = "_at_opentelemetry_slash_core";
      packageName = "@opentelemetry/core";
      version = "1.30.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/core/-/core-1.30.1.tgz";
        sha512 = "OOCM2C/QIURhJMuKaekP3TRBxBKxG/TWWA0TL2J6nXUtDnuCtccy49LUJF8xPFXMX+0LMcxFpCo8M9cGY1W6rQ==";
      };
    };
    "@opentelemetry/instrumentation-0.57.2" = {
      name = "_at_opentelemetry_slash_instrumentation";
      packageName = "@opentelemetry/instrumentation";
      version = "0.57.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation/-/instrumentation-0.57.2.tgz";
        sha512 = "BdBGhQBh8IjZ2oIIX6F2/Q3LKm/FDDKi6ccYKcBTeilh6SNdNKveDOLk73BkSJjQLJk6qe4Yh+hHw1UPhCDdrg==";
      };
    };
    "@opentelemetry/instrumentation-amqplib-0.46.1" = {
      name = "_at_opentelemetry_slash_instrumentation-amqplib";
      packageName = "@opentelemetry/instrumentation-amqplib";
      version = "0.46.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-amqplib/-/instrumentation-amqplib-0.46.1.tgz";
        sha512 = "AyXVnlCf/xV3K/rNumzKxZqsULyITJH6OVLiW6730JPRqWA7Zc9bvYoVNpN6iOpTU8CasH34SU/ksVJmObFibQ==";
      };
    };
    "@opentelemetry/instrumentation-connect-0.43.1" = {
      name = "_at_opentelemetry_slash_instrumentation-connect";
      packageName = "@opentelemetry/instrumentation-connect";
      version = "0.43.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-connect/-/instrumentation-connect-0.43.1.tgz";
        sha512 = "ht7YGWQuV5BopMcw5Q2hXn3I8eG8TH0J/kc/GMcW4CuNTgiP6wCu44BOnucJWL3CmFWaRHI//vWyAhaC8BwePw==";
      };
    };
    "@opentelemetry/instrumentation-dataloader-0.16.1" = {
      name = "_at_opentelemetry_slash_instrumentation-dataloader";
      packageName = "@opentelemetry/instrumentation-dataloader";
      version = "0.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-dataloader/-/instrumentation-dataloader-0.16.1.tgz";
        sha512 = "K/qU4CjnzOpNkkKO4DfCLSQshejRNAJtd4esgigo/50nxCB6XCyi1dhAblUHM9jG5dRm8eu0FB+t87nIo99LYQ==";
      };
    };
    "@opentelemetry/instrumentation-express-0.47.1" = {
      name = "_at_opentelemetry_slash_instrumentation-express";
      packageName = "@opentelemetry/instrumentation-express";
      version = "0.47.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-express/-/instrumentation-express-0.47.1.tgz";
        sha512 = "QNXPTWteDclR2B4pDFpz0TNghgB33UMjUt14B+BZPmtH1MwUFAfLHBaP5If0Z5NZC+jaH8oF2glgYjrmhZWmSw==";
      };
    };
    "@opentelemetry/instrumentation-fs-0.19.1" = {
      name = "_at_opentelemetry_slash_instrumentation-fs";
      packageName = "@opentelemetry/instrumentation-fs";
      version = "0.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-fs/-/instrumentation-fs-0.19.1.tgz";
        sha512 = "6g0FhB3B9UobAR60BGTcXg4IHZ6aaYJzp0Ki5FhnxyAPt8Ns+9SSvgcrnsN2eGmk3RWG5vYycUGOEApycQL24A==";
      };
    };
    "@opentelemetry/instrumentation-generic-pool-0.43.1" = {
      name = "_at_opentelemetry_slash_instrumentation-generic-pool";
      packageName = "@opentelemetry/instrumentation-generic-pool";
      version = "0.43.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-generic-pool/-/instrumentation-generic-pool-0.43.1.tgz";
        sha512 = "M6qGYsp1cURtvVLGDrPPZemMFEbuMmCXgQYTReC/IbimV5sGrLBjB+/hANUpRZjX67nGLdKSVLZuQQAiNz+sww==";
      };
    };
    "@opentelemetry/instrumentation-graphql-0.47.1" = {
      name = "_at_opentelemetry_slash_instrumentation-graphql";
      packageName = "@opentelemetry/instrumentation-graphql";
      version = "0.47.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-graphql/-/instrumentation-graphql-0.47.1.tgz";
        sha512 = "EGQRWMGqwiuVma8ZLAZnExQ7sBvbOx0N/AE/nlafISPs8S+QtXX+Viy6dcQwVWwYHQPAcuY3bFt3xgoAwb4ZNQ==";
      };
    };
    "@opentelemetry/instrumentation-hapi-0.45.2" = {
      name = "_at_opentelemetry_slash_instrumentation-hapi";
      packageName = "@opentelemetry/instrumentation-hapi";
      version = "0.45.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-hapi/-/instrumentation-hapi-0.45.2.tgz";
        sha512 = "7Ehow/7Wp3aoyCrZwQpU7a2CnoMq0XhIcioFuKjBb0PLYfBfmTsFTUyatlHu0fRxhwcRsSQRTvEhmZu8CppBpQ==";
      };
    };
    "@opentelemetry/instrumentation-http-0.57.2" = {
      name = "_at_opentelemetry_slash_instrumentation-http";
      packageName = "@opentelemetry/instrumentation-http";
      version = "0.57.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-http/-/instrumentation-http-0.57.2.tgz";
        sha512 = "1Uz5iJ9ZAlFOiPuwYg29Bf7bJJc/GeoeJIFKJYQf67nTVKFe8RHbEtxgkOmK4UGZNHKXcpW4P8cWBYzBn1USpg==";
      };
    };
    "@opentelemetry/instrumentation-ioredis-0.47.1" = {
      name = "_at_opentelemetry_slash_instrumentation-ioredis";
      packageName = "@opentelemetry/instrumentation-ioredis";
      version = "0.47.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-ioredis/-/instrumentation-ioredis-0.47.1.tgz";
        sha512 = "OtFGSN+kgk/aoKgdkKQnBsQFDiG8WdCxu+UrHr0bXScdAmtSzLSraLo7wFIb25RVHfRWvzI5kZomqJYEg/l1iA==";
      };
    };
    "@opentelemetry/instrumentation-kafkajs-0.7.1" = {
      name = "_at_opentelemetry_slash_instrumentation-kafkajs";
      packageName = "@opentelemetry/instrumentation-kafkajs";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-kafkajs/-/instrumentation-kafkajs-0.7.1.tgz";
        sha512 = "OtjaKs8H7oysfErajdYr1yuWSjMAectT7Dwr+axIoZqT9lmEOkD/H/3rgAs8h/NIuEi2imSXD+vL4MZtOuJfqQ==";
      };
    };
    "@opentelemetry/instrumentation-knex-0.44.1" = {
      name = "_at_opentelemetry_slash_instrumentation-knex";
      packageName = "@opentelemetry/instrumentation-knex";
      version = "0.44.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-knex/-/instrumentation-knex-0.44.1.tgz";
        sha512 = "U4dQxkNhvPexffjEmGwCq68FuftFK15JgUF05y/HlK3M6W/G2iEaACIfXdSnwVNe9Qh0sPfw8LbOPxrWzGWGMQ==";
      };
    };
    "@opentelemetry/instrumentation-koa-0.47.1" = {
      name = "_at_opentelemetry_slash_instrumentation-koa";
      packageName = "@opentelemetry/instrumentation-koa";
      version = "0.47.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-koa/-/instrumentation-koa-0.47.1.tgz";
        sha512 = "l/c+Z9F86cOiPJUllUCt09v+kICKvT+Vg1vOAJHtHPsJIzurGayucfCMq2acd/A/yxeNWunl9d9eqZ0G+XiI6A==";
      };
    };
    "@opentelemetry/instrumentation-lru-memoizer-0.44.1" = {
      name = "_at_opentelemetry_slash_instrumentation-lru-memoizer";
      packageName = "@opentelemetry/instrumentation-lru-memoizer";
      version = "0.44.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-lru-memoizer/-/instrumentation-lru-memoizer-0.44.1.tgz";
        sha512 = "5MPkYCvG2yw7WONEjYj5lr5JFehTobW7wX+ZUFy81oF2lr9IPfZk9qO+FTaM0bGEiymwfLwKe6jE15nHn1nmHg==";
      };
    };
    "@opentelemetry/instrumentation-mongodb-0.52.0" = {
      name = "_at_opentelemetry_slash_instrumentation-mongodb";
      packageName = "@opentelemetry/instrumentation-mongodb";
      version = "0.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-mongodb/-/instrumentation-mongodb-0.52.0.tgz";
        sha512 = "1xmAqOtRUQGR7QfJFfGV/M2kC7wmI2WgZdpru8hJl3S0r4hW0n3OQpEHlSGXJAaNFyvT+ilnwkT+g5L4ljHR6g==";
      };
    };
    "@opentelemetry/instrumentation-mongoose-0.46.1" = {
      name = "_at_opentelemetry_slash_instrumentation-mongoose";
      packageName = "@opentelemetry/instrumentation-mongoose";
      version = "0.46.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-mongoose/-/instrumentation-mongoose-0.46.1.tgz";
        sha512 = "3kINtW1LUTPkiXFRSSBmva1SXzS/72we/jL22N+BnF3DFcoewkdkHPYOIdAAk9gSicJ4d5Ojtt1/HeibEc5OQg==";
      };
    };
    "@opentelemetry/instrumentation-mysql-0.45.1" = {
      name = "_at_opentelemetry_slash_instrumentation-mysql";
      packageName = "@opentelemetry/instrumentation-mysql";
      version = "0.45.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-mysql/-/instrumentation-mysql-0.45.1.tgz";
        sha512 = "TKp4hQ8iKQsY7vnp/j0yJJ4ZsP109Ht6l4RHTj0lNEG1TfgTrIH5vJMbgmoYXWzNHAqBH2e7fncN12p3BP8LFg==";
      };
    };
    "@opentelemetry/instrumentation-mysql2-0.45.2" = {
      name = "_at_opentelemetry_slash_instrumentation-mysql2";
      packageName = "@opentelemetry/instrumentation-mysql2";
      version = "0.45.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-mysql2/-/instrumentation-mysql2-0.45.2.tgz";
        sha512 = "h6Ad60FjCYdJZ5DTz1Lk2VmQsShiViKe0G7sYikb0GHI0NVvApp2XQNRHNjEMz87roFttGPLHOYVPlfy+yVIhQ==";
      };
    };
    "@opentelemetry/instrumentation-pg-0.51.1" = {
      name = "_at_opentelemetry_slash_instrumentation-pg";
      packageName = "@opentelemetry/instrumentation-pg";
      version = "0.51.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-pg/-/instrumentation-pg-0.51.1.tgz";
        sha512 = "QxgjSrxyWZc7Vk+qGSfsejPVFL1AgAJdSBMYZdDUbwg730D09ub3PXScB9d04vIqPriZ+0dqzjmQx0yWKiCi2Q==";
      };
    };
    "@opentelemetry/instrumentation-redis-4-0.46.1" = {
      name = "_at_opentelemetry_slash_instrumentation-redis-4";
      packageName = "@opentelemetry/instrumentation-redis-4";
      version = "0.46.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-redis-4/-/instrumentation-redis-4-0.46.1.tgz";
        sha512 = "UMqleEoabYMsWoTkqyt9WAzXwZ4BlFZHO40wr3d5ZvtjKCHlD4YXLm+6OLCeIi/HkX7EXvQaz8gtAwkwwSEvcQ==";
      };
    };
    "@opentelemetry/instrumentation-tedious-0.18.1" = {
      name = "_at_opentelemetry_slash_instrumentation-tedious";
      packageName = "@opentelemetry/instrumentation-tedious";
      version = "0.18.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-tedious/-/instrumentation-tedious-0.18.1.tgz";
        sha512 = "5Cuy/nj0HBaH+ZJ4leuD7RjgvA844aY2WW+B5uLcWtxGjRZl3MNLuxnNg5DYWZNPO+NafSSnra0q49KWAHsKBg==";
      };
    };
    "@opentelemetry/instrumentation-undici-0.10.1" = {
      name = "_at_opentelemetry_slash_instrumentation-undici";
      packageName = "@opentelemetry/instrumentation-undici";
      version = "0.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/instrumentation-undici/-/instrumentation-undici-0.10.1.tgz";
        sha512 = "rkOGikPEyRpMCmNu9AQuV5dtRlDmJp2dK5sw8roVshAGoB6hH/3QjDtRhdwd75SsJwgynWUNRUYe0wAkTo16tQ==";
      };
    };
    "@opentelemetry/redis-common-0.36.2" = {
      name = "_at_opentelemetry_slash_redis-common";
      packageName = "@opentelemetry/redis-common";
      version = "0.36.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/redis-common/-/redis-common-0.36.2.tgz";
        sha512 = "faYX1N0gpLhej/6nyp6bgRjzAKXn5GOEMYY7YhciSfCoITAktLUtQ36d24QEWNA1/WA1y6qQunCe0OhHRkVl9g==";
      };
    };
    "@opentelemetry/resources-1.30.1" = {
      name = "_at_opentelemetry_slash_resources";
      packageName = "@opentelemetry/resources";
      version = "1.30.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/resources/-/resources-1.30.1.tgz";
        sha512 = "5UxZqiAgLYGFjS4s9qm5mBVo433u+dSPUFWVWXmLAD4wB65oMCoXaJP1KJa9DIYYMeHu3z4BZcStG3LC593cWA==";
      };
    };
    "@opentelemetry/sdk-trace-base-1.30.1" = {
      name = "_at_opentelemetry_slash_sdk-trace-base";
      packageName = "@opentelemetry/sdk-trace-base";
      version = "1.30.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/sdk-trace-base/-/sdk-trace-base-1.30.1.tgz";
        sha512 = "jVPgBbH1gCy2Lb7X0AVQ8XAfgg0pJ4nvl8/IiQA6nxOsPvS+0zMJaFSs2ltXe0J6C8dqjcnpyqINDJmU30+uOg==";
      };
    };
    "@opentelemetry/semantic-conventions-1.28.0" = {
      name = "_at_opentelemetry_slash_semantic-conventions";
      packageName = "@opentelemetry/semantic-conventions";
      version = "1.28.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/semantic-conventions/-/semantic-conventions-1.28.0.tgz";
        sha512 = "lp4qAiMTD4sNWW4DbKLBkfiMZ4jbAboJIGOQr5DvciMRI494OapieI9qiODpOt0XBr1LjIDy1xAGAnVs5supTA==";
      };
    };
    "@opentelemetry/semantic-conventions-1.37.0" = {
      name = "_at_opentelemetry_slash_semantic-conventions";
      packageName = "@opentelemetry/semantic-conventions";
      version = "1.37.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/semantic-conventions/-/semantic-conventions-1.37.0.tgz";
        sha512 = "JD6DerIKdJGmRp4jQyX5FlrQjA4tjOw1cvfsPAZXfOOEErMUHjPcPSICS+6WnM0nB0efSFARh0KAZss+bvExOA==";
      };
    };
    "@opentelemetry/sql-common-0.40.1" = {
      name = "_at_opentelemetry_slash_sql-common";
      packageName = "@opentelemetry/sql-common";
      version = "0.40.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@opentelemetry/sql-common/-/sql-common-0.40.1.tgz";
        sha512 = "nSDlnHSqzC3pXn/wZEZVLuAuJ1MYMXPBwtv2qAbCa3847SaHItdE7SzUq/Jtb0KZmh1zfAbNi3AAMjztTT4Ugg==";
      };
    };
    "@prisma/instrumentation-6.11.1" = {
      name = "_at_prisma_slash_instrumentation";
      packageName = "@prisma/instrumentation";
      version = "6.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/instrumentation/-/instrumentation-6.11.1.tgz";
        sha512 = "mrZOev24EDhnefmnZX7WVVT7v+r9LttPRqf54ONvj6re4XMF7wFTpK2tLJi4XHB7fFp/6xhYbgRel8YV7gQiyA==";
      };
    };
    "@sentry-internal/node-cpu-profiler-2.2.0" = {
      name = "_at_sentry-internal_slash_node-cpu-profiler";
      packageName = "@sentry-internal/node-cpu-profiler";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry-internal/node-cpu-profiler/-/node-cpu-profiler-2.2.0.tgz";
        sha512 = "oLHVYurqZfADPh5hvmQYS5qx8t0UZzT2u6+/68VXsFruQEOnYJTODKgU3BVLmemRs3WE6kCJjPeFdHVYOQGSzQ==";
      };
    };
    "@sentry/core-9.46.0" = {
      name = "_at_sentry_slash_core";
      packageName = "@sentry/core";
      version = "9.46.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/core/-/core-9.46.0.tgz";
        sha512 = "it7JMFqxVproAgEtbLgCVBYtQ9fIb+Bu0JD+cEplTN/Ukpe6GaolyYib5geZqslVxhp2sQgT+58aGvfd/k0N8Q==";
      };
    };
    "@sentry/node-9.46.0" = {
      name = "_at_sentry_slash_node";
      packageName = "@sentry/node";
      version = "9.46.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/node/-/node-9.46.0.tgz";
        sha512 = "pRLqAcd7GTGvN8gex5FtkQR5Mcol8gOy1WlyZZFq4rBbVtMbqKOQRhohwqnb+YrnmtFpj7IZ7KNDo077MvNeOQ==";
      };
    };
    "@sentry/node-core-9.46.0" = {
      name = "_at_sentry_slash_node-core";
      packageName = "@sentry/node-core";
      version = "9.46.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/node-core/-/node-core-9.46.0.tgz";
        sha512 = "XRVu5pqoklZeh4wqhxCLZkz/ipoKhitctgEFXX9Yh1e1BoHM2pIxT52wf+W6hHM676TFmFXW3uKBjsmRM3AjgA==";
      };
    };
    "@sentry/opentelemetry-9.46.0" = {
      name = "_at_sentry_slash_opentelemetry";
      packageName = "@sentry/opentelemetry";
      version = "9.46.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/opentelemetry/-/opentelemetry-9.46.0.tgz";
        sha512 = "w2zTxqrdmwRok0cXBoh+ksXdGRUHUZhlpfL/H2kfTodOL+Mk8rW72qUmfqQceXoqgbz8UyK8YgJbyt+XS5H4Qg==";
      };
    };
    "@sentry/profiling-node-9.46.0" = {
      name = "_at_sentry_slash_profiling-node";
      packageName = "@sentry/profiling-node";
      version = "9.46.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/profiling-node/-/profiling-node-9.46.0.tgz";
        sha512 = "MPNjVx6m9fn+HUU1FGr5PzgAKLLJA6eXXf+xobtVk+jNo9e0YczUUcnSTJz+VeIUG2joFm9sPfRjYLyONNLuxQ==";
      };
    };
    "@types/connect-3.4.38" = {
      name = "_at_types_slash_connect";
      packageName = "@types/connect";
      version = "3.4.38";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/connect/-/connect-3.4.38.tgz";
        sha512 = "K6uROf1LD88uDQqJCktA4yzL1YYAK6NgfsI0v/mTgyPKWsX1CnJ0XPSDhViejru1GcRkLWb8RlzFYJRqGUbaug==";
      };
    };
    "@types/mysql-2.15.26" = {
      name = "_at_types_slash_mysql";
      packageName = "@types/mysql";
      version = "2.15.26";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mysql/-/mysql-2.15.26.tgz";
        sha512 = "DSLCOXhkvfS5WNNPbfn2KdICAmk8lLc+/PNvnPnF7gOdMZCxopXduqv0OQ13y/yA/zXTSikZZqVgybUxOEg6YQ==";
      };
    };
    "@types/node-24.9.2" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "24.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-24.9.2.tgz";
        sha512 = "uWN8YqxXxqFMX2RqGOrumsKeti4LlmIMIyV0lgut4jx7KQBcBiW6vkDtIBvHnHIquwNfJhk8v2OtmO8zXWHfPA==";
      };
    };
    "@types/pg-8.6.1" = {
      name = "_at_types_slash_pg";
      packageName = "@types/pg";
      version = "8.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/pg/-/pg-8.6.1.tgz";
        sha512 = "1Kc4oAGzAl7uqUStZCDvaLFqZrW9qWSjXOmBfdgyBP5La7Us6Mg4GBvRlSoaZMhQF/zSj1C8CtKMBkoiT8eL8w==";
      };
    };
    "@types/pg-pool-2.0.6" = {
      name = "_at_types_slash_pg-pool";
      packageName = "@types/pg-pool";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/pg-pool/-/pg-pool-2.0.6.tgz";
        sha512 = "TaAUE5rq2VQYxab5Ts7WZhKNmuN78Q6PiFonTDdpbx8a1H0M1vhy3rhiMjl+e2iHmogyMw7jZF4FrE6eJUy5HQ==";
      };
    };
    "@types/shimmer-1.2.0" = {
      name = "_at_types_slash_shimmer";
      packageName = "@types/shimmer";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/shimmer/-/shimmer-1.2.0.tgz";
        sha512 = "UE7oxhQLLd9gub6JKIAhDq06T0F6FnztwMNRvYgjeQSBeMc1ZG/tA47EwfduvkuQS8apbkM/lpLpWsaCeYsXVg==";
      };
    };
    "@types/tedious-4.0.14" = {
      name = "_at_types_slash_tedious";
      packageName = "@types/tedious";
      version = "4.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/tedious/-/tedious-4.0.14.tgz";
        sha512 = "KHPsfX/FoVbUGbyYvk1q9MMQHLPeRZhRJZdO45Q4YjvFkv4hMNghCWTvy7rdKessBsmtz4euWCWAB6/tVpI1Iw==";
      };
    };
    "acorn-8.15.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.15.0.tgz";
        sha512 = "NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg==";
      };
    };
    "acorn-import-attributes-1.9.5" = {
      name = "acorn-import-attributes";
      packageName = "acorn-import-attributes";
      version = "1.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-import-attributes/-/acorn-import-attributes-1.9.5.tgz";
        sha512 = "n02Vykv5uA3eHGM/Z2dQrcD56kL8TyDb2p1+0P83PClMnC/nc+anbQRhIOWnSq4Ke/KvDPrY3C9hDtC/A3eHnQ==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-2.0.2" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.2.tgz";
        sha512 = "Jt0vHyM+jmUBqojB7E1NIYadt0vI0Qxjxd2TErW94wDz+E2LAm5vKMXXwg6ZZBTHPuUlDgQHKXvjGBdfcF1ZDQ==";
      };
    };
    "cjs-module-lexer-1.4.3" = {
      name = "cjs-module-lexer";
      packageName = "cjs-module-lexer";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cjs-module-lexer/-/cjs-module-lexer-1.4.3.tgz";
        sha512 = "9z8TZaGM1pfswYeXrUpzPrkx8UnWYdhJclsiYMm6x/w5+nN+8Tf/LnAgfLGQCm59qAOxU8WwHEq2vNwF6i4j+Q==";
      };
    };
    "debug-4.4.3" = {
      name = "debug";
      packageName = "debug";
      version = "4.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz";
        sha512 = "RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
      };
    };
    "detect-libc-2.1.2" = {
      name = "detect-libc";
      packageName = "detect-libc";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-libc/-/detect-libc-2.1.2.tgz";
        sha512 = "Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==";
      };
    };
    "fdir-6.5.0" = {
      name = "fdir";
      packageName = "fdir";
      version = "6.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fdir/-/fdir-6.5.0.tgz";
        sha512 = "tIbYtZbucOs0BRGqPJkshJUYdL+SDH7dVM8gjy+ERp3WAUjLEFJE+02kanyHtwjWOnwrKYBiwAmM0p4kLJAnXg==";
      };
    };
    "forwarded-parse-2.1.2" = {
      name = "forwarded-parse";
      packageName = "forwarded-parse";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded-parse/-/forwarded-parse-2.1.2.tgz";
        sha512 = "alTFZZQDKMporBH77856pXgzhEzaUVmLCDk+egLgIgHst3Tpndzz8MnKe+GzRJRfvVdn69HhpW7cmXzvtLvJAw==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "fzf-0.5.2" = {
      name = "fzf";
      packageName = "fzf";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fzf/-/fzf-0.5.2.tgz";
        sha512 = "Tt4kuxLXFKHy8KT40zwsUPUkg1CrsgY25FxA2U/j/0WgEDCk3ddc/zLTCCcbSHX9FcKtLuVaDGtGE/STWC+j3Q==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "import-in-the-middle-1.15.0" = {
      name = "import-in-the-middle";
      packageName = "import-in-the-middle";
      version = "1.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-in-the-middle/-/import-in-the-middle-1.15.0.tgz";
        sha512 = "bpQy+CrsRmYmoPMAE/0G33iwRqwW4ouqdRg8jgbH3aKuCtOc8lxgmYXg2dMM92CRiGP660EtBcymH/eVUpCSaA==";
      };
    };
    "is-core-module-2.16.1" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.16.1.tgz";
        sha512 = "UfoeMA6fIJ8wTYFEUjelnaGI67v6+N7qXJEvQuIGa99l4xsCruSYOVSQ0uPANn4dAzm8lkYPaKLrrijLq7x23w==";
      };
    };
    "minimatch-9.0.5" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "9.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-9.0.5.tgz";
        sha512 = "G6T0ZX48xgozx7587koeX9Ys2NYy6Gmv//P89sEte9V9whIapMNF4idKxnW2QtCcLiTWlb/wfCabAtAFWhhBow==";
      };
    };
    "module-details-from-path-1.0.4" = {
      name = "module-details-from-path";
      packageName = "module-details-from-path";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/module-details-from-path/-/module-details-from-path-1.0.4.tgz";
        sha512 = "EGWKgxALGMgzvxYF1UyGTy0HXX/2vHLkw6+NvDKW2jypWbHpjQuj4UMcqQWXHERJhVGKikolT06G3bcKe4fi7w==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "node-abi-3.79.0" = {
      name = "node-abi";
      packageName = "node-abi";
      version = "3.79.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-abi/-/node-abi-3.79.0.tgz";
        sha512 = "Pr/5KdBQGG8TirdkS0qN3B+f3eo8zTOfZQWAxHoJqopMz2/uvRnG+S4fWu/6AZxKei2CP2p/psdQ5HFC2Ap5BA==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "pg-int8-1.0.1" = {
      name = "pg-int8";
      packageName = "pg-int8";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-int8/-/pg-int8-1.0.1.tgz";
        sha512 = "WCtabS6t3c8SkpDBUlb1kjOs7l66xsGdKpIPZsg4wR+B3+u9UAum2odSsF9tnvxg80h4ZxLWMy4pRjOsFIqQpw==";
      };
    };
    "pg-protocol-1.10.3" = {
      name = "pg-protocol";
      packageName = "pg-protocol";
      version = "1.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-protocol/-/pg-protocol-1.10.3.tgz";
        sha512 = "6DIBgBQaTKDJyxnXaLiLR8wBpQQcGWuAESkRBX/t6OwA8YsqP+iVSiond2EDy6Y/dsGk8rh/jtax3js5NeV7JQ==";
      };
    };
    "pg-types-2.2.0" = {
      name = "pg-types";
      packageName = "pg-types";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-types/-/pg-types-2.2.0.tgz";
        sha512 = "qTAAlrEsl8s4OiEQY69wDvcMIdQN6wdz5ojQiOy6YRMuynxenON0O5oCpJI6lshc6scgAY8qvJ2On/p+CXY0GA==";
      };
    };
    "picomatch-4.0.3" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-4.0.3.tgz";
        sha512 = "5gTmgEY/sqK6gFXLIsQNH19lWb4ebPDLA4SdLP7dsWkIXHWlG66oPuVvXSGFPppYZz8ZDZq0dYYrbHfBCVUb1Q==";
      };
    };
    "postgres-array-2.0.0" = {
      name = "postgres-array";
      packageName = "postgres-array";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-array/-/postgres-array-2.0.0.tgz";
        sha512 = "VpZrUqU5A69eQyW2c5CA1jtLecCsN2U/bD6VilrFDWq5+5UIEVO7nazS3TEcHf1zuPYO/sqGvUvW62g86RXZuA==";
      };
    };
    "postgres-bytea-1.0.0" = {
      name = "postgres-bytea";
      packageName = "postgres-bytea";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-bytea/-/postgres-bytea-1.0.0.tgz";
        sha512 = "xy3pmLuQqRBZBXDULy7KbaitYqLcmxigw14Q5sj8QBVLqEwXfeybIKVWiqAXTlcvdvb0+xkOtDbfQMOf4lST1w==";
      };
    };
    "postgres-date-1.0.7" = {
      name = "postgres-date";
      packageName = "postgres-date";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-date/-/postgres-date-1.0.7.tgz";
        sha512 = "suDmjLVQg78nMK2UZ454hAG+OAW+HQPZ6n++TNDUX+L0+uUlLywnoxJKDou51Zm+zTCjrCl0Nq6J9C5hP9vK/Q==";
      };
    };
    "postgres-interval-1.2.0" = {
      name = "postgres-interval";
      packageName = "postgres-interval";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-interval/-/postgres-interval-1.2.0.tgz";
        sha512 = "9ZhXKM/rw350N1ovuWHbGxnGh/SNJ4cnxHiM0rxE4VN41wsg8P8zWn9hv/buK00RP4WvlOyr/RBDiptyxVbkZQ==";
      };
    };
    "require-in-the-middle-7.5.2" = {
      name = "require-in-the-middle";
      packageName = "require-in-the-middle";
      version = "7.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-in-the-middle/-/require-in-the-middle-7.5.2.tgz";
        sha512 = "gAZ+kLqBdHarXB64XpAe2VCjB7rIRv+mU8tfRWziHRJ5umKsIHN2tLLv6EtMw7WCdP19S0ERVMldNvxYCHnhSQ==";
      };
    };
    "resolve-1.22.11" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.11.tgz";
        sha512 = "RfqAvLnMl313r7c9oclB1HhUEAezcpLjz95wFH4LVuhk9JF/r22qmVP9AMmOU4vMX7Q8pN8jwNg/CSpdFnMjTQ==";
      };
    };
    "semver-7.7.3" = {
      name = "semver";
      packageName = "semver";
      version = "7.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.7.3.tgz";
        sha512 = "SdsKMrI9TdgjdweUSR9MweHA4EJ8YxHn8DFaDisvhVlUOe4BF1tLD7GAj0lIqWVl+dPb/rExr0Btby5loQm20Q==";
      };
    };
    "shimmer-1.2.1" = {
      name = "shimmer";
      packageName = "shimmer";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shimmer/-/shimmer-1.2.1.tgz";
        sha512 = "sQTKC1Re/rM6XyFM6fIAGHRPVGvyXfgzIDvzoq608vM+jeyVD0Tu1E6Np0Kc2zAIFWIj963V2800iF/9LPieQw==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "undici-types-7.16.0" = {
      name = "undici-types";
      packageName = "undici-types";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici-types/-/undici-types-7.16.0.tgz";
        sha512 = "Zz+aZWSj8LE6zoxD+xrjh4VfkIG8Ya6LvYkZqtUQGJPZjYl53ypCaUwWqo7eI0x66KBGeRo+mlBEkMSeSZ38Nw==";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
  };
in
{
  "@continuedev/cli" = nodeEnv.buildNodePackage {
    name = "_at_continuedev_slash_cli";
    packageName = "@continuedev/cli";
    version = "1.5.8";
    src = fetchurl {
      url = "https://registry.npmjs.org/@continuedev/cli/-/cli-1.5.8.tgz";
      sha512 = "0zt2blqyom21F1SUKvI0+ZcqSnniTg5Y79b4aYX1Uor0sRosvCoikOSLFgNwp15ora0Bd8sAy8JMXj5k7vqnPg==";
    };
    dependencies = [
      sources."@opentelemetry/api-1.9.0"
      sources."@opentelemetry/api-logs-0.57.2"
      sources."@opentelemetry/context-async-hooks-1.30.1"
      (sources."@opentelemetry/core-1.30.1" // {
        dependencies = [
          sources."@opentelemetry/semantic-conventions-1.28.0"
        ];
      })
      sources."@opentelemetry/instrumentation-0.57.2"
      sources."@opentelemetry/instrumentation-amqplib-0.46.1"
      sources."@opentelemetry/instrumentation-connect-0.43.1"
      sources."@opentelemetry/instrumentation-dataloader-0.16.1"
      sources."@opentelemetry/instrumentation-express-0.47.1"
      sources."@opentelemetry/instrumentation-fs-0.19.1"
      sources."@opentelemetry/instrumentation-generic-pool-0.43.1"
      sources."@opentelemetry/instrumentation-graphql-0.47.1"
      sources."@opentelemetry/instrumentation-hapi-0.45.2"
      (sources."@opentelemetry/instrumentation-http-0.57.2" // {
        dependencies = [
          sources."@opentelemetry/semantic-conventions-1.28.0"
        ];
      })
      sources."@opentelemetry/instrumentation-ioredis-0.47.1"
      sources."@opentelemetry/instrumentation-kafkajs-0.7.1"
      sources."@opentelemetry/instrumentation-knex-0.44.1"
      sources."@opentelemetry/instrumentation-koa-0.47.1"
      sources."@opentelemetry/instrumentation-lru-memoizer-0.44.1"
      sources."@opentelemetry/instrumentation-mongodb-0.52.0"
      sources."@opentelemetry/instrumentation-mongoose-0.46.1"
      sources."@opentelemetry/instrumentation-mysql-0.45.1"
      sources."@opentelemetry/instrumentation-mysql2-0.45.2"
      sources."@opentelemetry/instrumentation-pg-0.51.1"
      sources."@opentelemetry/instrumentation-redis-4-0.46.1"
      sources."@opentelemetry/instrumentation-tedious-0.18.1"
      sources."@opentelemetry/instrumentation-undici-0.10.1"
      sources."@opentelemetry/redis-common-0.36.2"
      (sources."@opentelemetry/resources-1.30.1" // {
        dependencies = [
          sources."@opentelemetry/semantic-conventions-1.28.0"
        ];
      })
      (sources."@opentelemetry/sdk-trace-base-1.30.1" // {
        dependencies = [
          sources."@opentelemetry/semantic-conventions-1.28.0"
        ];
      })
      sources."@opentelemetry/semantic-conventions-1.37.0"
      sources."@opentelemetry/sql-common-0.40.1"
      sources."@prisma/instrumentation-6.11.1"
      sources."@sentry-internal/node-cpu-profiler-2.2.0"
      sources."@sentry/core-9.46.0"
      sources."@sentry/node-9.46.0"
      sources."@sentry/node-core-9.46.0"
      sources."@sentry/opentelemetry-9.46.0"
      sources."@sentry/profiling-node-9.46.0"
      sources."@types/connect-3.4.38"
      sources."@types/mysql-2.15.26"
      sources."@types/node-24.9.2"
      sources."@types/pg-8.6.1"
      sources."@types/pg-pool-2.0.6"
      sources."@types/shimmer-1.2.0"
      sources."@types/tedious-4.0.14"
      sources."acorn-8.15.0"
      sources."acorn-import-attributes-1.9.5"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-2.0.2"
      sources."cjs-module-lexer-1.4.3"
      sources."debug-4.4.3"
      sources."detect-libc-2.1.2"
      sources."fdir-6.5.0"
      sources."forwarded-parse-2.1.2"
      sources."function-bind-1.1.2"
      sources."fzf-0.5.2"
      sources."hasown-2.0.2"
      sources."import-in-the-middle-1.15.0"
      sources."is-core-module-2.16.1"
      sources."minimatch-9.0.5"
      sources."module-details-from-path-1.0.4"
      sources."ms-2.1.3"
      sources."node-abi-3.79.0"
      sources."path-parse-1.0.7"
      sources."pg-int8-1.0.1"
      sources."pg-protocol-1.10.3"
      sources."pg-types-2.2.0"
      sources."picomatch-4.0.3"
      sources."postgres-array-2.0.0"
      sources."postgres-bytea-1.0.0"
      sources."postgres-date-1.0.7"
      sources."postgres-interval-1.2.0"
      sources."require-in-the-middle-7.5.2"
      sources."resolve-1.22.11"
      sources."semver-7.7.3"
      sources."shimmer-1.2.1"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."undici-types-7.16.0"
      sources."xtend-4.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Continue CLI";
      homepage = "https://continue.dev";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
